/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ServiceTicketsRouteImport } from './routes/service-tickets'
import { Route as ServicePlansRouteImport } from './routes/service-plans'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as LeadInboxRouteImport } from './routes/lead-inbox'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'

const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceTicketsRoute = ServiceTicketsRouteImport.update({
  id: '/service-tickets',
  path: '/service-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicePlansRoute = ServicePlansRouteImport.update({
  id: '/service-plans',
  path: '/service-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadInboxRoute = LeadInboxRouteImport.update({
  id: '/lead-inbox',
  path: '/lead-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/lead-inbox': typeof LeadInboxRoute
  '/opportunities': typeof OpportunitiesRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/service-plans': typeof ServicePlansRoute
  '/service-tickets': typeof ServiceTicketsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/lead-inbox': typeof LeadInboxRoute
  '/opportunities': typeof OpportunitiesRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/service-plans': typeof ServicePlansRoute
  '/service-tickets': typeof ServiceTicketsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/companies': typeof CompaniesRoute
  '/contacts': typeof ContactsRoute
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/lead-inbox': typeof LeadInboxRoute
  '/opportunities': typeof OpportunitiesRoute
  '/payments': typeof PaymentsRoute
  '/projects': typeof ProjectsRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotes': typeof QuotesRoute
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/service-plans': typeof ServicePlansRoute
  '/service-tickets': typeof ServiceTicketsRoute
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/companies'
    | '/contacts'
    | '/inbox'
    | '/inventory'
    | '/invoices'
    | '/lead-inbox'
    | '/opportunities'
    | '/payments'
    | '/projects'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/scheduling'
    | '/service-plans'
    | '/service-tickets'
    | '/team'
    | '/vendors'
    | '/work-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/companies'
    | '/contacts'
    | '/inbox'
    | '/inventory'
    | '/invoices'
    | '/lead-inbox'
    | '/opportunities'
    | '/payments'
    | '/projects'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/scheduling'
    | '/service-plans'
    | '/service-tickets'
    | '/team'
    | '/vendors'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/companies'
    | '/contacts'
    | '/inbox'
    | '/inventory'
    | '/invoices'
    | '/lead-inbox'
    | '/opportunities'
    | '/payments'
    | '/projects'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/scheduling'
    | '/service-plans'
    | '/service-tickets'
    | '/team'
    | '/vendors'
    | '/work-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactsRoute: typeof ContactsRoute
  InboxRoute: typeof InboxRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadInboxRoute: typeof LeadInboxRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PaymentsRoute: typeof PaymentsRoute
  ProjectsRoute: typeof ProjectsRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  QuotesRoute: typeof QuotesRoute
  ReportsRoute: typeof ReportsRoute
  SchedulingRoute: typeof SchedulingRoute
  ServicePlansRoute: typeof ServicePlansRoute
  ServiceTicketsRoute: typeof ServiceTicketsRoute
  TeamRoute: typeof TeamRoute
  VendorsRoute: typeof VendorsRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-tickets': {
      id: '/service-tickets'
      path: '/service-tickets'
      fullPath: '/service-tickets'
      preLoaderRoute: typeof ServiceTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-plans': {
      id: '/service-plans'
      path: '/service-plans'
      fullPath: '/service-plans'
      preLoaderRoute: typeof ServicePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-inbox': {
      id: '/lead-inbox'
      path: '/lead-inbox'
      fullPath: '/lead-inbox'
      preLoaderRoute: typeof LeadInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CompaniesRoute: CompaniesRoute,
  ContactsRoute: ContactsRoute,
  InboxRoute: InboxRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  LeadInboxRoute: LeadInboxRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PaymentsRoute: PaymentsRoute,
  ProjectsRoute: ProjectsRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  QuotesRoute: QuotesRoute,
  ReportsRoute: ReportsRoute,
  SchedulingRoute: SchedulingRoute,
  ServicePlansRoute: ServicePlansRoute,
  ServiceTicketsRoute: ServiceTicketsRoute,
  TeamRoute: TeamRoute,
  VendorsRoute: VendorsRoute,
  WorkOrdersRoute: WorkOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
