/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LeadInboxRouteImport } from './routes/lead-inbox'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrdersIndexRouteImport } from './routes/work-orders/index'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as QuotesIndexRouteImport } from './routes/quotes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PlannerIndexRouteImport } from './routes/planner/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as WorkOrdersWorkOrderIdRouteImport } from './routes/work-orders/$workOrderId'
import { Route as SettingsQuoteTemplatesRouteImport } from './routes/settings/quote-templates'
import { Route as ServiceServiceTicketsRouteImport } from './routes/service/service-tickets'
import { Route as ServiceServicePlansRouteImport } from './routes/service/service-plans'
import { Route as QuotesNewRouteImport } from './routes/quotes/new'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes/$quoteId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as InventoryStockRouteImport } from './routes/inventory/stock'
import { Route as InventoryCatalogRouteImport } from './routes/inventory/catalog'
import { Route as FinancePaymentsRouteImport } from './routes/finance/payments'
import { Route as FinanceInvoicesRouteImport } from './routes/finance/invoices'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'

const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadInboxRoute = LeadInboxRouteImport.update({
  id: '/lead-inbox',
  path: '/lead-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersIndexRoute = WorkOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkOrdersRoute,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRoute,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuotesRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const PlannerIndexRoute = PlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlannerRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompaniesRoute,
} as any)
const WorkOrdersWorkOrderIdRoute = WorkOrdersWorkOrderIdRouteImport.update({
  id: '/$workOrderId',
  path: '/$workOrderId',
  getParentRoute: () => WorkOrdersRoute,
} as any)
const SettingsQuoteTemplatesRoute = SettingsQuoteTemplatesRouteImport.update({
  id: '/quote-templates',
  path: '/quote-templates',
  getParentRoute: () => SettingsRoute,
} as any)
const ServiceServiceTicketsRoute = ServiceServiceTicketsRouteImport.update({
  id: '/service-tickets',
  path: '/service-tickets',
  getParentRoute: () => ServiceRoute,
} as any)
const ServiceServicePlansRoute = ServiceServicePlansRouteImport.update({
  id: '/service-plans',
  path: '/service-plans',
  getParentRoute: () => ServiceRoute,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotesRoute,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => QuotesRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const InventoryStockRoute = InventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryCatalogRoute = InventoryCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => InventoryRoute,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => FinanceRoute,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/finance': typeof FinanceRouteWithChildren
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/lead-inbox': typeof LeadInboxRoute
  '/operations': typeof OperationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/planner': typeof PlannerRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/service': typeof ServiceRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inventory/catalog': typeof InventoryCatalogRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/service/service-plans': typeof ServiceServicePlansRoute
  '/service/service-tickets': typeof ServiceServiceTicketsRoute
  '/settings/quote-templates': typeof SettingsQuoteTemplatesRoute
  '/work-orders/$workOrderId': typeof WorkOrdersWorkOrderIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/inbox': typeof InboxRoute
  '/lead-inbox': typeof LeadInboxRoute
  '/operations': typeof OperationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inventory/catalog': typeof InventoryCatalogRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/service/service-plans': typeof ServiceServicePlansRoute
  '/service/service-tickets': typeof ServiceServiceTicketsRoute
  '/settings/quote-templates': typeof SettingsQuoteTemplatesRoute
  '/work-orders/$workOrderId': typeof WorkOrdersWorkOrderIdRoute
  '/companies': typeof CompaniesIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/planner': typeof PlannerIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/service': typeof ServiceIndexRoute
  '/work-orders': typeof WorkOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/finance': typeof FinanceRouteWithChildren
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/lead-inbox': typeof LeadInboxRoute
  '/operations': typeof OperationsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/planner': typeof PlannerRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/service': typeof ServiceRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/team': typeof TeamRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRouteWithChildren
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inventory/catalog': typeof InventoryCatalogRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/quotes/$quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
  '/service/service-plans': typeof ServiceServicePlansRoute
  '/service/service-tickets': typeof ServiceServiceTicketsRoute
  '/settings/quote-templates': typeof SettingsQuoteTemplatesRoute
  '/work-orders/$workOrderId': typeof WorkOrdersWorkOrderIdRoute
  '/companies/': typeof CompaniesIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/planner/': typeof PlannerIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/work-orders/': typeof WorkOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/companies'
    | '/contacts'
    | '/finance'
    | '/inbox'
    | '/inventory'
    | '/lead-inbox'
    | '/operations'
    | '/opportunities'
    | '/planner'
    | '/projects'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/scheduling'
    | '/service'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/work-orders'
    | '/companies/$companyId'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inventory/catalog'
    | '/inventory/stock'
    | '/projects/$projectId'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/service/service-plans'
    | '/service/service-tickets'
    | '/settings/quote-templates'
    | '/work-orders/$workOrderId'
    | '/companies/'
    | '/finance/'
    | '/inventory/'
    | '/planner/'
    | '/projects/'
    | '/quotes/'
    | '/service/'
    | '/work-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/contacts'
    | '/inbox'
    | '/lead-inbox'
    | '/operations'
    | '/opportunities'
    | '/purchase-orders'
    | '/reports'
    | '/scheduling'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/companies/$companyId'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inventory/catalog'
    | '/inventory/stock'
    | '/projects/$projectId'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/service/service-plans'
    | '/service/service-tickets'
    | '/settings/quote-templates'
    | '/work-orders/$workOrderId'
    | '/companies'
    | '/finance'
    | '/inventory'
    | '/planner'
    | '/projects'
    | '/quotes'
    | '/service'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/companies'
    | '/contacts'
    | '/finance'
    | '/inbox'
    | '/inventory'
    | '/lead-inbox'
    | '/operations'
    | '/opportunities'
    | '/planner'
    | '/projects'
    | '/purchase-orders'
    | '/quotes'
    | '/reports'
    | '/scheduling'
    | '/service'
    | '/settings'
    | '/team'
    | '/vendors'
    | '/work-orders'
    | '/companies/$companyId'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inventory/catalog'
    | '/inventory/stock'
    | '/projects/$projectId'
    | '/quotes/$quoteId'
    | '/quotes/new'
    | '/service/service-plans'
    | '/service/service-tickets'
    | '/settings/quote-templates'
    | '/work-orders/$workOrderId'
    | '/companies/'
    | '/finance/'
    | '/inventory/'
    | '/planner/'
    | '/projects/'
    | '/quotes/'
    | '/service/'
    | '/work-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  InboxRoute: typeof InboxRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LeadInboxRoute: typeof LeadInboxRoute
  OperationsRoute: typeof OperationsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PlannerRoute: typeof PlannerRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  QuotesRoute: typeof QuotesRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SchedulingRoute: typeof SchedulingRoute
  ServiceRoute: typeof ServiceRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  TeamRoute: typeof TeamRoute
  VendorsRoute: typeof VendorsRoute
  WorkOrdersRoute: typeof WorkOrdersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-inbox': {
      id: '/lead-inbox'
      path: '/lead-inbox'
      fullPath: '/lead-inbox'
      preLoaderRoute: typeof LeadInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/': {
      id: '/work-orders/'
      path: '/'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof WorkOrdersIndexRouteImport
      parentRoute: typeof WorkOrdersRoute
    }
    '/service/': {
      id: '/service/'
      path: '/'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/planner/': {
      id: '/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof PlannerIndexRouteImport
      parentRoute: typeof PlannerRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/companies/': {
      id: '/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/work-orders/$workOrderId': {
      id: '/work-orders/$workOrderId'
      path: '/$workOrderId'
      fullPath: '/work-orders/$workOrderId'
      preLoaderRoute: typeof WorkOrdersWorkOrderIdRouteImport
      parentRoute: typeof WorkOrdersRoute
    }
    '/settings/quote-templates': {
      id: '/settings/quote-templates'
      path: '/quote-templates'
      fullPath: '/settings/quote-templates'
      preLoaderRoute: typeof SettingsQuoteTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/service/service-tickets': {
      id: '/service/service-tickets'
      path: '/service-tickets'
      fullPath: '/service/service-tickets'
      preLoaderRoute: typeof ServiceServiceTicketsRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/service/service-plans': {
      id: '/service/service-plans'
      path: '/service-plans'
      fullPath: '/service/service-plans'
      preLoaderRoute: typeof ServiceServicePlansRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/quotes/$quoteId': {
      id: '/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/inventory/stock': {
      id: '/inventory/stock'
      path: '/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof InventoryStockRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/catalog': {
      id: '/inventory/catalog'
      path: '/catalog'
      fullPath: '/inventory/catalog'
      preLoaderRoute: typeof InventoryCatalogRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/invoices': {
      id: '/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface FinanceRouteChildren {
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface InventoryRouteChildren {
  InventoryCatalogRoute: typeof InventoryCatalogRoute
  InventoryStockRoute: typeof InventoryStockRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryCatalogRoute: InventoryCatalogRoute,
  InventoryStockRoute: InventoryStockRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface PlannerRouteChildren {
  PlannerIndexRoute: typeof PlannerIndexRoute
}

const PlannerRouteChildren: PlannerRouteChildren = {
  PlannerIndexRoute: PlannerIndexRoute,
}

const PlannerRouteWithChildren =
  PlannerRoute._addFileChildren(PlannerRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface QuotesRouteChildren {
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRoute
  QuotesNewRoute: typeof QuotesNewRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesQuoteIdRoute: QuotesQuoteIdRoute,
  QuotesNewRoute: QuotesNewRoute,
  QuotesIndexRoute: QuotesIndexRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

interface ServiceRouteChildren {
  ServiceServicePlansRoute: typeof ServiceServicePlansRoute
  ServiceServiceTicketsRoute: typeof ServiceServiceTicketsRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
}

const ServiceRouteChildren: ServiceRouteChildren = {
  ServiceServicePlansRoute: ServiceServicePlansRoute,
  ServiceServiceTicketsRoute: ServiceServiceTicketsRoute,
  ServiceIndexRoute: ServiceIndexRoute,
}

const ServiceRouteWithChildren =
  ServiceRoute._addFileChildren(ServiceRouteChildren)

interface SettingsRouteChildren {
  SettingsQuoteTemplatesRoute: typeof SettingsQuoteTemplatesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsQuoteTemplatesRoute: SettingsQuoteTemplatesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WorkOrdersRouteChildren {
  WorkOrdersWorkOrderIdRoute: typeof WorkOrdersWorkOrderIdRoute
  WorkOrdersIndexRoute: typeof WorkOrdersIndexRoute
}

const WorkOrdersRouteChildren: WorkOrdersRouteChildren = {
  WorkOrdersWorkOrderIdRoute: WorkOrdersWorkOrderIdRoute,
  WorkOrdersIndexRoute: WorkOrdersIndexRoute,
}

const WorkOrdersRouteWithChildren = WorkOrdersRoute._addFileChildren(
  WorkOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  ContactsRoute: ContactsRoute,
  FinanceRoute: FinanceRouteWithChildren,
  InboxRoute: InboxRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LeadInboxRoute: LeadInboxRoute,
  OperationsRoute: OperationsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PlannerRoute: PlannerRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  QuotesRoute: QuotesRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SchedulingRoute: SchedulingRoute,
  ServiceRoute: ServiceRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  TeamRoute: TeamRoute,
  VendorsRoute: VendorsRoute,
  WorkOrdersRoute: WorkOrdersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
