/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ServiceIndexRouteImport } from './routes/service/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as OperationsIndexRouteImport } from './routes/operations/index'
import { Route as InventoryIndexRouteImport } from './routes/inventory/index'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as SettingsServicePlanTiersRouteImport } from './routes/settings/service-plan-tiers'
import { Route as SettingsQuoteTemplatesRouteImport } from './routes/settings/quote-templates'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsCompanyRouteImport } from './routes/settings/company'
import { Route as SettingsRolesRouteImport } from './routes/settings/roles'
import { Route as ServiceServiceTicketsRouteImport } from './routes/service/service-tickets'
import { Route as ServiceServicePlansRouteImport } from './routes/service/service-plans'
import { Route as SalesQuotesRouteImport } from './routes/sales/quotes'
import { Route as SalesOpportunitiesRouteImport } from './routes/sales/opportunities'
import { Route as SalesLeadInboxRouteImport } from './routes/sales/lead-inbox'
import { Route as OperationsWorkOrdersRouteImport } from './routes/operations/work-orders'
import { Route as OperationsTeamRouteImport } from './routes/operations/team'
import { Route as OperationsSchedulingRouteImport } from './routes/operations/scheduling'
import { Route as OperationsProjectsRouteImport } from './routes/operations/projects'
import { Route as OperationsPlannerRouteImport } from './routes/operations/planner'
import { Route as InventoryVendorsRouteImport } from './routes/inventory/vendors'
import { Route as InventoryStockRouteImport } from './routes/inventory/stock'
import { Route as InventoryPurchaseOrdersRouteImport } from './routes/inventory/purchase-orders'
import { Route as InventoryCatalogRouteImport } from './routes/inventory/catalog'
import { Route as FinancePaymentsRouteImport } from './routes/finance/payments'
import { Route as FinanceInvoicesRouteImport } from './routes/finance/invoices'
import { Route as CrmContactsRouteImport } from './routes/crm/contacts'
import { Route as CrmCompaniesRouteImport } from './routes/crm/companies'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SalesQuotesIndexRouteImport } from './routes/sales/quotes/index'
import { Route as OperationsWorkOrdersIndexRouteImport } from './routes/operations/work-orders/index'
import { Route as OperationsProjectsIndexRouteImport } from './routes/operations/projects/index'
import { Route as OperationsPlannerIndexRouteImport } from './routes/operations/planner/index'
import { Route as CrmCompaniesIndexRouteImport } from './routes/crm/companies/index'
import { Route as SalesQuotesNewRouteImport } from './routes/sales/quotes/new'
import { Route as SalesQuotesQuoteIdRouteImport } from './routes/sales/quotes/$quoteId'
import { Route as OperationsWorkOrdersWorkOrderIdRouteImport } from './routes/operations/work-orders/$workOrderId'
import { Route as OperationsProjectsProjectIdRouteImport } from './routes/operations/projects/$projectId'
import { Route as CrmCompaniesCompanyIdRouteImport } from './routes/crm/companies/$companyId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ServiceIndexRoute = ServiceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const SettingsServicePlanTiersRoute =
  SettingsServicePlanTiersRouteImport.update({
    id: '/service-plan-tiers',
    path: '/service-plan-tiers',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsQuoteTemplatesRoute = SettingsQuoteTemplatesRouteImport.update({
  id: '/quote-templates',
  path: '/quote-templates',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => SettingsRoute,
} as any)
const ServiceServiceTicketsRoute = ServiceServiceTicketsRouteImport.update({
  id: '/service-tickets',
  path: '/service-tickets',
  getParentRoute: () => ServiceRoute,
} as any)
const ServiceServicePlansRoute = ServiceServicePlansRouteImport.update({
  id: '/service-plans',
  path: '/service-plans',
  getParentRoute: () => ServiceRoute,
} as any)
const SalesQuotesRoute = SalesQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => SalesRoute,
} as any)
const SalesOpportunitiesRoute = SalesOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => SalesRoute,
} as any)
const SalesLeadInboxRoute = SalesLeadInboxRouteImport.update({
  id: '/lead-inbox',
  path: '/lead-inbox',
  getParentRoute: () => SalesRoute,
} as any)
const OperationsWorkOrdersRoute = OperationsWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsTeamRoute = OperationsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsSchedulingRoute = OperationsSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsProjectsRoute = OperationsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsPlannerRoute = OperationsPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => OperationsRoute,
} as any)
const InventoryVendorsRoute = InventoryVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryStockRoute = InventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryPurchaseOrdersRoute = InventoryPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryCatalogRoute = InventoryCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => InventoryRoute,
} as any)
const FinancePaymentsRoute = FinancePaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceInvoicesRoute = FinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => FinanceRoute,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => CrmRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const SalesQuotesIndexRoute = SalesQuotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesQuotesRoute,
} as any)
const OperationsWorkOrdersIndexRoute =
  OperationsWorkOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperationsWorkOrdersRoute,
  } as any)
const OperationsProjectsIndexRoute = OperationsProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsProjectsRoute,
} as any)
const OperationsPlannerIndexRoute = OperationsPlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsPlannerRoute,
} as any)
const CrmCompaniesIndexRoute = CrmCompaniesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmCompaniesRoute,
} as any)
const SalesQuotesNewRoute = SalesQuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesQuotesRoute,
} as any)
const SalesQuotesQuoteIdRoute = SalesQuotesQuoteIdRouteImport.update({
  id: '/$quoteId',
  path: '/$quoteId',
  getParentRoute: () => SalesQuotesRoute,
} as any)
const OperationsWorkOrdersWorkOrderIdRoute =
  OperationsWorkOrdersWorkOrderIdRouteImport.update({
    id: '/$workOrderId',
    path: '/$workOrderId',
    getParentRoute: () => OperationsWorkOrdersRoute,
  } as any)
const OperationsProjectsProjectIdRoute =
  OperationsProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => OperationsProjectsRoute,
  } as any)
const CrmCompaniesCompanyIdRoute = CrmCompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CrmCompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/service': typeof ServiceRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/crm/companies': typeof CrmCompaniesRouteWithChildren
  '/crm/contacts': typeof CrmContactsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inventory/catalog': typeof InventoryCatalogRoute
  '/inventory/purchase-orders': typeof InventoryPurchaseOrdersRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/inventory/vendors': typeof InventoryVendorsRoute
  '/operations/planner': typeof OperationsPlannerRouteWithChildren
  '/operations/projects': typeof OperationsProjectsRouteWithChildren
  '/operations/scheduling': typeof OperationsSchedulingRoute
  '/operations/team': typeof OperationsTeamRoute
  '/operations/work-orders': typeof OperationsWorkOrdersRouteWithChildren
  '/sales/lead-inbox': typeof SalesLeadInboxRoute
  '/sales/opportunities': typeof SalesOpportunitiesRoute
  '/sales/quotes': typeof SalesQuotesRouteWithChildren
  '/service/service-plans': typeof ServiceServicePlansRoute
  '/service/service-tickets': typeof ServiceServiceTicketsRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/quote-templates': typeof SettingsQuoteTemplatesRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/service-plan-tiers': typeof SettingsServicePlanTiersRoute
  '/crm/': typeof CrmIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/crm/companies/$companyId': typeof CrmCompaniesCompanyIdRoute
  '/operations/projects/$projectId': typeof OperationsProjectsProjectIdRoute
  '/operations/work-orders/$workOrderId': typeof OperationsWorkOrdersWorkOrderIdRoute
  '/sales/quotes/$quoteId': typeof SalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/crm/companies/': typeof CrmCompaniesIndexRoute
  '/operations/planner/': typeof OperationsPlannerIndexRoute
  '/operations/projects/': typeof OperationsProjectsIndexRoute
  '/operations/work-orders/': typeof OperationsWorkOrdersIndexRoute
  '/sales/quotes/': typeof SalesQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/inbox': typeof InboxRoute
  '/reports': typeof ReportsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inventory/catalog': typeof InventoryCatalogRoute
  '/inventory/purchase-orders': typeof InventoryPurchaseOrdersRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/inventory/vendors': typeof InventoryVendorsRoute
  '/operations/scheduling': typeof OperationsSchedulingRoute
  '/operations/team': typeof OperationsTeamRoute
  '/sales/lead-inbox': typeof SalesLeadInboxRoute
  '/sales/opportunities': typeof SalesOpportunitiesRoute
  '/service/service-plans': typeof ServiceServicePlansRoute
  '/service/service-tickets': typeof ServiceServiceTicketsRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/quote-templates': typeof SettingsQuoteTemplatesRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/service-plan-tiers': typeof SettingsServicePlanTiersRoute
  '/crm': typeof CrmIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/operations': typeof OperationsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/service': typeof ServiceIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/crm/companies/$companyId': typeof CrmCompaniesCompanyIdRoute
  '/operations/projects/$projectId': typeof OperationsProjectsProjectIdRoute
  '/operations/work-orders/$workOrderId': typeof OperationsWorkOrdersWorkOrderIdRoute
  '/sales/quotes/$quoteId': typeof SalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/crm/companies': typeof CrmCompaniesIndexRoute
  '/operations/planner': typeof OperationsPlannerIndexRoute
  '/operations/projects': typeof OperationsProjectsIndexRoute
  '/operations/work-orders': typeof OperationsWorkOrdersIndexRoute
  '/sales/quotes': typeof SalesQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/inbox': typeof InboxRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/operations': typeof OperationsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/service': typeof ServiceRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/crm/companies': typeof CrmCompaniesRouteWithChildren
  '/crm/contacts': typeof CrmContactsRoute
  '/finance/invoices': typeof FinanceInvoicesRoute
  '/finance/payments': typeof FinancePaymentsRoute
  '/inventory/catalog': typeof InventoryCatalogRoute
  '/inventory/purchase-orders': typeof InventoryPurchaseOrdersRoute
  '/inventory/stock': typeof InventoryStockRoute
  '/inventory/vendors': typeof InventoryVendorsRoute
  '/operations/planner': typeof OperationsPlannerRouteWithChildren
  '/operations/projects': typeof OperationsProjectsRouteWithChildren
  '/operations/scheduling': typeof OperationsSchedulingRoute
  '/operations/team': typeof OperationsTeamRoute
  '/operations/work-orders': typeof OperationsWorkOrdersRouteWithChildren
  '/sales/lead-inbox': typeof SalesLeadInboxRoute
  '/sales/opportunities': typeof SalesOpportunitiesRoute
  '/sales/quotes': typeof SalesQuotesRouteWithChildren
  '/service/service-plans': typeof ServiceServicePlansRoute
  '/service/service-tickets': typeof ServiceServiceTicketsRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/quote-templates': typeof SettingsQuoteTemplatesRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/service-plan-tiers': typeof SettingsServicePlanTiersRoute
  '/crm/': typeof CrmIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/operations/': typeof OperationsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/service/': typeof ServiceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/crm/companies/$companyId': typeof CrmCompaniesCompanyIdRoute
  '/operations/projects/$projectId': typeof OperationsProjectsProjectIdRoute
  '/operations/work-orders/$workOrderId': typeof OperationsWorkOrdersWorkOrderIdRoute
  '/sales/quotes/$quoteId': typeof SalesQuotesQuoteIdRoute
  '/sales/quotes/new': typeof SalesQuotesNewRoute
  '/crm/companies/': typeof CrmCompaniesIndexRoute
  '/operations/planner/': typeof OperationsPlannerIndexRoute
  '/operations/projects/': typeof OperationsProjectsIndexRoute
  '/operations/work-orders/': typeof OperationsWorkOrdersIndexRoute
  '/sales/quotes/': typeof SalesQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crm'
    | '/finance'
    | '/inbox'
    | '/inventory'
    | '/operations'
    | '/reports'
    | '/sales'
    | '/service'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/crm/companies'
    | '/crm/contacts'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inventory/catalog'
    | '/inventory/purchase-orders'
    | '/inventory/stock'
    | '/inventory/vendors'
    | '/operations/planner'
    | '/operations/projects'
    | '/operations/scheduling'
    | '/operations/team'
    | '/operations/work-orders'
    | '/sales/lead-inbox'
    | '/sales/opportunities'
    | '/sales/quotes'
    | '/service/service-plans'
    | '/service/service-tickets'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/quote-templates'
    | '/settings/roles'
    | '/settings/service-plan-tiers'
    | '/crm/'
    | '/finance/'
    | '/inventory/'
    | '/operations/'
    | '/sales/'
    | '/service/'
    | '/settings/'
    | '/crm/companies/$companyId'
    | '/operations/projects/$projectId'
    | '/operations/work-orders/$workOrderId'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/crm/companies/'
    | '/operations/planner/'
    | '/operations/projects/'
    | '/operations/work-orders/'
    | '/sales/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/inbox'
    | '/reports'
    | '/auth/login'
    | '/auth/signup'
    | '/crm/contacts'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inventory/catalog'
    | '/inventory/purchase-orders'
    | '/inventory/stock'
    | '/inventory/vendors'
    | '/operations/scheduling'
    | '/operations/team'
    | '/sales/lead-inbox'
    | '/sales/opportunities'
    | '/service/service-plans'
    | '/service/service-tickets'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/quote-templates'
    | '/settings/roles'
    | '/settings/service-plan-tiers'
    | '/crm'
    | '/finance'
    | '/inventory'
    | '/operations'
    | '/sales'
    | '/service'
    | '/settings'
    | '/crm/companies/$companyId'
    | '/operations/projects/$projectId'
    | '/operations/work-orders/$workOrderId'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/crm/companies'
    | '/operations/planner'
    | '/operations/projects'
    | '/operations/work-orders'
    | '/sales/quotes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/crm'
    | '/finance'
    | '/inbox'
    | '/inventory'
    | '/operations'
    | '/reports'
    | '/sales'
    | '/service'
    | '/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/crm/companies'
    | '/crm/contacts'
    | '/finance/invoices'
    | '/finance/payments'
    | '/inventory/catalog'
    | '/inventory/purchase-orders'
    | '/inventory/stock'
    | '/inventory/vendors'
    | '/operations/planner'
    | '/operations/projects'
    | '/operations/scheduling'
    | '/operations/team'
    | '/operations/work-orders'
    | '/sales/lead-inbox'
    | '/sales/opportunities'
    | '/sales/quotes'
    | '/service/service-plans'
    | '/service/service-tickets'
    | '/settings/company'
    | '/settings/integrations'
    | '/settings/quote-templates'
    | '/settings/roles'
    | '/settings/service-plan-tiers'
    | '/crm/'
    | '/finance/'
    | '/inventory/'
    | '/operations/'
    | '/sales/'
    | '/service/'
    | '/settings/'
    | '/crm/companies/$companyId'
    | '/operations/projects/$projectId'
    | '/operations/work-orders/$workOrderId'
    | '/sales/quotes/$quoteId'
    | '/sales/quotes/new'
    | '/crm/companies/'
    | '/operations/planner/'
    | '/operations/projects/'
    | '/operations/work-orders/'
    | '/sales/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CrmRoute: typeof CrmRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  InboxRoute: typeof InboxRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  OperationsRoute: typeof OperationsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRouteWithChildren
  ServiceRoute: typeof ServiceRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/service/': {
      id: '/service/'
      path: '/'
      fullPath: '/service/'
      preLoaderRoute: typeof ServiceIndexRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/settings/service-plan-tiers': {
      id: '/settings/service-plan-tiers'
      path: '/service-plan-tiers'
      fullPath: '/settings/service-plan-tiers'
      preLoaderRoute: typeof SettingsServicePlanTiersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/quote-templates': {
      id: '/settings/quote-templates'
      path: '/quote-templates'
      fullPath: '/settings/quote-templates'
      preLoaderRoute: typeof SettingsQuoteTemplatesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/service/service-tickets': {
      id: '/service/service-tickets'
      path: '/service-tickets'
      fullPath: '/service/service-tickets'
      preLoaderRoute: typeof ServiceServiceTicketsRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/service/service-plans': {
      id: '/service/service-plans'
      path: '/service-plans'
      fullPath: '/service/service-plans'
      preLoaderRoute: typeof ServiceServicePlansRouteImport
      parentRoute: typeof ServiceRoute
    }
    '/sales/quotes': {
      id: '/sales/quotes'
      path: '/quotes'
      fullPath: '/sales/quotes'
      preLoaderRoute: typeof SalesQuotesRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/opportunities': {
      id: '/sales/opportunities'
      path: '/opportunities'
      fullPath: '/sales/opportunities'
      preLoaderRoute: typeof SalesOpportunitiesRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/lead-inbox': {
      id: '/sales/lead-inbox'
      path: '/lead-inbox'
      fullPath: '/sales/lead-inbox'
      preLoaderRoute: typeof SalesLeadInboxRouteImport
      parentRoute: typeof SalesRoute
    }
    '/operations/work-orders': {
      id: '/operations/work-orders'
      path: '/work-orders'
      fullPath: '/operations/work-orders'
      preLoaderRoute: typeof OperationsWorkOrdersRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/team': {
      id: '/operations/team'
      path: '/team'
      fullPath: '/operations/team'
      preLoaderRoute: typeof OperationsTeamRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/scheduling': {
      id: '/operations/scheduling'
      path: '/scheduling'
      fullPath: '/operations/scheduling'
      preLoaderRoute: typeof OperationsSchedulingRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/projects': {
      id: '/operations/projects'
      path: '/projects'
      fullPath: '/operations/projects'
      preLoaderRoute: typeof OperationsProjectsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/planner': {
      id: '/operations/planner'
      path: '/planner'
      fullPath: '/operations/planner'
      preLoaderRoute: typeof OperationsPlannerRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/inventory/vendors': {
      id: '/inventory/vendors'
      path: '/vendors'
      fullPath: '/inventory/vendors'
      preLoaderRoute: typeof InventoryVendorsRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/stock': {
      id: '/inventory/stock'
      path: '/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof InventoryStockRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/purchase-orders': {
      id: '/inventory/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/inventory/purchase-orders'
      preLoaderRoute: typeof InventoryPurchaseOrdersRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/catalog': {
      id: '/inventory/catalog'
      path: '/catalog'
      fullPath: '/inventory/catalog'
      preLoaderRoute: typeof InventoryCatalogRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/finance/payments': {
      id: '/finance/payments'
      path: '/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof FinancePaymentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/invoices': {
      id: '/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof FinanceInvoicesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/sales/quotes/': {
      id: '/sales/quotes/'
      path: '/'
      fullPath: '/sales/quotes/'
      preLoaderRoute: typeof SalesQuotesIndexRouteImport
      parentRoute: typeof SalesQuotesRoute
    }
    '/operations/work-orders/': {
      id: '/operations/work-orders/'
      path: '/'
      fullPath: '/operations/work-orders/'
      preLoaderRoute: typeof OperationsWorkOrdersIndexRouteImport
      parentRoute: typeof OperationsWorkOrdersRoute
    }
    '/operations/projects/': {
      id: '/operations/projects/'
      path: '/'
      fullPath: '/operations/projects/'
      preLoaderRoute: typeof OperationsProjectsIndexRouteImport
      parentRoute: typeof OperationsProjectsRoute
    }
    '/operations/planner/': {
      id: '/operations/planner/'
      path: '/'
      fullPath: '/operations/planner/'
      preLoaderRoute: typeof OperationsPlannerIndexRouteImport
      parentRoute: typeof OperationsPlannerRoute
    }
    '/crm/companies/': {
      id: '/crm/companies/'
      path: '/'
      fullPath: '/crm/companies/'
      preLoaderRoute: typeof CrmCompaniesIndexRouteImport
      parentRoute: typeof CrmCompaniesRoute
    }
    '/sales/quotes/new': {
      id: '/sales/quotes/new'
      path: '/new'
      fullPath: '/sales/quotes/new'
      preLoaderRoute: typeof SalesQuotesNewRouteImport
      parentRoute: typeof SalesQuotesRoute
    }
    '/sales/quotes/$quoteId': {
      id: '/sales/quotes/$quoteId'
      path: '/$quoteId'
      fullPath: '/sales/quotes/$quoteId'
      preLoaderRoute: typeof SalesQuotesQuoteIdRouteImport
      parentRoute: typeof SalesQuotesRoute
    }
    '/operations/work-orders/$workOrderId': {
      id: '/operations/work-orders/$workOrderId'
      path: '/$workOrderId'
      fullPath: '/operations/work-orders/$workOrderId'
      preLoaderRoute: typeof OperationsWorkOrdersWorkOrderIdRouteImport
      parentRoute: typeof OperationsWorkOrdersRoute
    }
    '/operations/projects/$projectId': {
      id: '/operations/projects/$projectId'
      path: '/$projectId'
      fullPath: '/operations/projects/$projectId'
      preLoaderRoute: typeof OperationsProjectsProjectIdRouteImport
      parentRoute: typeof OperationsProjectsRoute
    }
    '/crm/companies/$companyId': {
      id: '/crm/companies/$companyId'
      path: '/$companyId'
      fullPath: '/crm/companies/$companyId'
      preLoaderRoute: typeof CrmCompaniesCompanyIdRouteImport
      parentRoute: typeof CrmCompaniesRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CrmCompaniesRouteChildren {
  CrmCompaniesCompanyIdRoute: typeof CrmCompaniesCompanyIdRoute
  CrmCompaniesIndexRoute: typeof CrmCompaniesIndexRoute
}

const CrmCompaniesRouteChildren: CrmCompaniesRouteChildren = {
  CrmCompaniesCompanyIdRoute: CrmCompaniesCompanyIdRoute,
  CrmCompaniesIndexRoute: CrmCompaniesIndexRoute,
}

const CrmCompaniesRouteWithChildren = CrmCompaniesRoute._addFileChildren(
  CrmCompaniesRouteChildren,
)

interface CrmRouteChildren {
  CrmCompaniesRoute: typeof CrmCompaniesRouteWithChildren
  CrmContactsRoute: typeof CrmContactsRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmCompaniesRoute: CrmCompaniesRouteWithChildren,
  CrmContactsRoute: CrmContactsRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface FinanceRouteChildren {
  FinanceInvoicesRoute: typeof FinanceInvoicesRoute
  FinancePaymentsRoute: typeof FinancePaymentsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceInvoicesRoute: FinanceInvoicesRoute,
  FinancePaymentsRoute: FinancePaymentsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface InventoryRouteChildren {
  InventoryCatalogRoute: typeof InventoryCatalogRoute
  InventoryPurchaseOrdersRoute: typeof InventoryPurchaseOrdersRoute
  InventoryStockRoute: typeof InventoryStockRoute
  InventoryVendorsRoute: typeof InventoryVendorsRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryCatalogRoute: InventoryCatalogRoute,
  InventoryPurchaseOrdersRoute: InventoryPurchaseOrdersRoute,
  InventoryStockRoute: InventoryStockRoute,
  InventoryVendorsRoute: InventoryVendorsRoute,
  InventoryIndexRoute: InventoryIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface OperationsPlannerRouteChildren {
  OperationsPlannerIndexRoute: typeof OperationsPlannerIndexRoute
}

const OperationsPlannerRouteChildren: OperationsPlannerRouteChildren = {
  OperationsPlannerIndexRoute: OperationsPlannerIndexRoute,
}

const OperationsPlannerRouteWithChildren =
  OperationsPlannerRoute._addFileChildren(OperationsPlannerRouteChildren)

interface OperationsProjectsRouteChildren {
  OperationsProjectsProjectIdRoute: typeof OperationsProjectsProjectIdRoute
  OperationsProjectsIndexRoute: typeof OperationsProjectsIndexRoute
}

const OperationsProjectsRouteChildren: OperationsProjectsRouteChildren = {
  OperationsProjectsProjectIdRoute: OperationsProjectsProjectIdRoute,
  OperationsProjectsIndexRoute: OperationsProjectsIndexRoute,
}

const OperationsProjectsRouteWithChildren =
  OperationsProjectsRoute._addFileChildren(OperationsProjectsRouteChildren)

interface OperationsWorkOrdersRouteChildren {
  OperationsWorkOrdersWorkOrderIdRoute: typeof OperationsWorkOrdersWorkOrderIdRoute
  OperationsWorkOrdersIndexRoute: typeof OperationsWorkOrdersIndexRoute
}

const OperationsWorkOrdersRouteChildren: OperationsWorkOrdersRouteChildren = {
  OperationsWorkOrdersWorkOrderIdRoute: OperationsWorkOrdersWorkOrderIdRoute,
  OperationsWorkOrdersIndexRoute: OperationsWorkOrdersIndexRoute,
}

const OperationsWorkOrdersRouteWithChildren =
  OperationsWorkOrdersRoute._addFileChildren(OperationsWorkOrdersRouteChildren)

interface OperationsRouteChildren {
  OperationsPlannerRoute: typeof OperationsPlannerRouteWithChildren
  OperationsProjectsRoute: typeof OperationsProjectsRouteWithChildren
  OperationsSchedulingRoute: typeof OperationsSchedulingRoute
  OperationsTeamRoute: typeof OperationsTeamRoute
  OperationsWorkOrdersRoute: typeof OperationsWorkOrdersRouteWithChildren
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsPlannerRoute: OperationsPlannerRouteWithChildren,
  OperationsProjectsRoute: OperationsProjectsRouteWithChildren,
  OperationsSchedulingRoute: OperationsSchedulingRoute,
  OperationsTeamRoute: OperationsTeamRoute,
  OperationsWorkOrdersRoute: OperationsWorkOrdersRouteWithChildren,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

interface SalesQuotesRouteChildren {
  SalesQuotesQuoteIdRoute: typeof SalesQuotesQuoteIdRoute
  SalesQuotesNewRoute: typeof SalesQuotesNewRoute
  SalesQuotesIndexRoute: typeof SalesQuotesIndexRoute
}

const SalesQuotesRouteChildren: SalesQuotesRouteChildren = {
  SalesQuotesQuoteIdRoute: SalesQuotesQuoteIdRoute,
  SalesQuotesNewRoute: SalesQuotesNewRoute,
  SalesQuotesIndexRoute: SalesQuotesIndexRoute,
}

const SalesQuotesRouteWithChildren = SalesQuotesRoute._addFileChildren(
  SalesQuotesRouteChildren,
)

interface SalesRouteChildren {
  SalesLeadInboxRoute: typeof SalesLeadInboxRoute
  SalesOpportunitiesRoute: typeof SalesOpportunitiesRoute
  SalesQuotesRoute: typeof SalesQuotesRouteWithChildren
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesLeadInboxRoute: SalesLeadInboxRoute,
  SalesOpportunitiesRoute: SalesOpportunitiesRoute,
  SalesQuotesRoute: SalesQuotesRouteWithChildren,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

interface ServiceRouteChildren {
  ServiceServicePlansRoute: typeof ServiceServicePlansRoute
  ServiceServiceTicketsRoute: typeof ServiceServiceTicketsRoute
  ServiceIndexRoute: typeof ServiceIndexRoute
}

const ServiceRouteChildren: ServiceRouteChildren = {
  ServiceServicePlansRoute: ServiceServicePlansRoute,
  ServiceServiceTicketsRoute: ServiceServiceTicketsRoute,
  ServiceIndexRoute: ServiceIndexRoute,
}

const ServiceRouteWithChildren =
  ServiceRoute._addFileChildren(ServiceRouteChildren)

interface SettingsRouteChildren {
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsQuoteTemplatesRoute: typeof SettingsQuoteTemplatesRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsServicePlanTiersRoute: typeof SettingsServicePlanTiersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsQuoteTemplatesRoute: SettingsQuoteTemplatesRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsServicePlanTiersRoute: SettingsServicePlanTiersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CrmRoute: CrmRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  InboxRoute: InboxRoute,
  InventoryRoute: InventoryRouteWithChildren,
  OperationsRoute: OperationsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRouteWithChildren,
  ServiceRoute: ServiceRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
